cdmi/urls.py
from django.conf.urls import url

from . import views

app_name = 'cdmi'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^browse/(?P<site>[0-9]+)/(?P<path>.*)$', views.BrowserView.as_view(), name='browse'),
    url(r'^browse/(?P<site>[0-9]+)$', views.BrowserView.as_view(), kwargs={'path': ''}, name='browse'),
    url(r'^browse/(?P<path>.*)$', views.BrowserView.as_view(), kwargs={'site': None}, name='browse'),
    url(r'^upload/(?P<site>[0-9]+)/(?P<path>.*)$', views.upload, name='upload'),
    url(r'^mkdir/(?P<site>[0-9]+)/(?P<path>.*)$', views.mkdir, name='mkdir'),
    url(r'^update/(?P<site>[0-9]+)/(?P<path>.*)$', views.update, name='update'),
    url(r'^delete/(?P<site>[0-9]+)/(?P<path>.*)$', views.delete, name='delete'),
    url(r'^info/(?P<site>[0-9]+)/(?P<path>.*)$', views.object_info, name='object_info'),
]

cdmiweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

#lambda request: ListView.as_view(queryset=Resources.objects.filter(user=request.user.username), ...)(request)
urlpatterns = [
    #  url(r'^admin/filebrowser/', include(site.urls)),
    #  url(r'^grappelli/', include('grappelli.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^openid/', include('openid.urls')),
    url(r'^cdmi/', include('cdmi.urls')),
    url(r'^admin/', admin.site.urls),
]

openid/urls.py
from django.conf.urls import url

from . import views

app_name = 'openid'
urlpatterns = [
    url(r'^$', views.openid_login, name='openid'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.openid_logout, name='logout'),
]

cdmi/models.py
import os
import shutil
import tempfile
import logging

from django.db import models
from django.core.files import storage
from django.urls import reverse
from django.forms import ValidationError

import webdav.client as webdav


logger = logging.getLogger(__name__)


class FileSystemStorage(storage.FileSystemStorage):
    access_type = 'local File system'

    def ensure_connected(self, *args, **kwargs):
        # Nothing needs to be done to connect to the local filesystem
        pass

    def mkdir(self, name):
        os.makedirs(os.path.join(self.location, name), exist_ok=True)

    def delete(self, name):
        try:
            super().delete(name)
        except IsADirectoryError:
            # https://code.djangoproject.com/ticket/27836
            shutil.rmtree(self.path(name))

    def store(self, name, content, max_length=None):
        logger.debug("Try to save file with...")
        logger.debug("location: {}".format(self.location))
        logger.debug("base_url: {}".format(self.base_url))
        logger.debug("name: {}".format(name))
        logger.debug("content: {}".format(str(content)))

        import os
        with open(os.path.join(self.location, name), 'wb') as f:
            f.write(content.file.read())

        #self.save(name, content, max_length)


class WebDAVServer(models.Model, storage.Storage):
    hostname = models.URLField()
    login = models.CharField(max_length=200, blank=True, default='')
    passwd = models.CharField(max_length=200, blank=True, default='')

    access_type = 'WebDAV'

    def __str__(self):
        return self.hostname

    def ensure_connected(self, access_token=None):
        if not hasattr(self, 'connection'):
            options = dict()
            options['webdav_hostname'] = self.hostname
            if self.login and self.passwd:
                options['webdav_login'] = self.login
                options['webdav_password'] = self.passwd
            elif access_token:
                options['webdav_token'] = access_token

            logger.debug("WebDAV: Connecting to {}".format(options))
            self.connection = webdav.Client(options)

    def delete(self, name):
        self.ensure_connected()
        self.connection.clean(name)

    def exists(self, name):
        self.ensure_connected()
        self.connection.check(name)

    def listdir(self, path):
        self.ensure_connected()
        self.connection.list(path)

    def open(self, name, mode='rb'):
        self.ensure_connected()
        tmp = tempfile.NamedTemporaryFile()
        self.connection.download_sync(
            remote_path=name,
            local_path=tmp.name)

        tmp.seek(0)
        return tmp

    def store(self, name, content, max_length=None):
        self.ensure_connected()
        tmp = tempfile.NamedTemporaryFile()
        tmp.write(content.read())

        self.connection.upload_sync(
            remote_path=name,
            local_path=tmp.name)

    def mkdir(self, name):
        self.ensure_connected()
        self.connection.mkdir(name)


class Site(models.Model):
    site_name = models.CharField(max_length=200)
    site_uri = models.URLField()
    logo_uri = models.URLField(blank=True)
    auth = models.CharField(
        default='bearer',
        choices=[
            ('bearer', 'Bearer token authentication'),
            # Useful for testing
            ('basic', 'HTTP basic authentication with restadmin:restadmin')],
        max_length=10)
    browser_path = models.CharField(
        blank=True, default='', max_length=128)

    browser_webdav = models.ForeignKey(
        WebDAVServer,
        blank=True, null=True, on_delete=models.SET_NULL)

    root_container = models.CharField(max_length=200, blank=True, default='')

    default = models.BooleanField(default=False)

    last_modified = models.DateTimeField(auto_now=True)

    def clean(self):
        if self.default:
            for site in Site.objects.exclude(pk=self.pk).filter(default=True):
                site.default = False
                site.save()
        elif Site.objects.filter(default=True).count() <= 0:
            raise ValidationError("Exactly one site in the database needs to be marked 'Default'")

    def __str__(self):
        return self.site_name

    @property
    def can_browse(self):
        return hasattr(self, 'storage')

    @property
    def storage(self):
        if self.browser_path:
            return FileSystemStorage(
                location=self.browser_path,
                base_url=reverse('cdmi:browse', args=[self.id, '']))
        elif self.browser_webdav:
            return self.browser_webdav
        else:
            raise AttributeError("'Site' object {} has no attribute 'storage'".format(self))


class StorageType(models.Model):
    type_name = models.CharField(max_length=200)
    logo_uri = models.URLField(blank=True)

    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.site_name

cdmi/views.py
import os
import logging
import re

from requests.compat import urlsplit

from django.shortcuts import redirect
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.sessions.models import Session

from webdav.connection import NotConnection, RemoteParentNotFound

from .models import Site
from . import cdmi, browser
from .cdmi import CdmiError

logger = logging.getLogger(__name__)


def true_path(apparent_path, site, user):
    if site.can_browse:
        prefix = os.path.join(site.root_container, user.username)
    else:
        prefix = site.root_container

    return os.path.join(prefix, re.sub('^/', '', apparent_path))


def has_access_token(user):
    for session in Session.objects.all():
        data = session.get_decoded()
        if '_auth_user_id' in data and int(data['_auth_user_id']) == user.id:
            return 'access_token' in data

    return False


def handle_update_object(request, site, path):
    qos = request.POST['qos']
    capabilities = urlsplit(qos).path

    response = cdmi.put_capabilities_class(
        site, path, request.session['access_token'],
        request.POST['type'] == 'Directory',
        capabilities)

    logger.debug(response)

    return response


@user_passes_test(has_access_token)
def object_info(request, site, path):
    # Basically, this is a CDMI proxy for the jQuery
    site = Site.objects.get(id=site)
    path = re.sub('/+', '/', path)
    cdmi_path = path
    if not (path.startswith('cdmi_') or path.startswith('/cdmi_')):
        cdmi_path = true_path(path, site, request.user)

    try:
        object_info = cdmi.get_status(
            site, cdmi_path, request.session['access_token'])
    except CdmiError as e:
        logger.warning('{}: {}'.format(e.dict.get('url', site.site_uri), e.dict['msg']))

        return JsonResponse({
            'error': e.dict['msg'],
            'site': site.site_uri,
            'url': e.dict['url']
        })
    else:
        return JsonResponse(object_info)


@csrf_exempt
@user_passes_test(has_access_token)
def update(request, site, path):
    site = Site.objects.get(id=site)
    path = re.sub('/+', '/', path)
    cdmi_path = true_path(path, site, request.user)

    if request.method == 'POST':
        if 'qos' in request.POST and 'type' in request.POST:
            logger.debug("Change {} to {}".format(
                cdmi_path, request.POST['qos']))
            response = handle_update_object(request, site, cdmi_path)
            return JsonResponse(response, status=200)
        else:
            return JsonResponse({'missing_parameters': ['qos', 'type']},
                                status=400)
    else:
        return JsonResponse({'message': 'Use POST'}, status=405)


@user_passes_test(has_access_token)
def delete(request, site, path):
    site = Site.objects.get(id=site)
    path = re.sub('/+', '/', path)
    cdmi_path = true_path(path, site, request.user)

    if request.method == 'POST' and 'name' in request.POST and site.can_browse:
        browser.handle_delete_object(
            site,
            request.POST['name'],
            cdmi_path,
            request.session['access_token'])

        messages.success(request, '{} deleted'.format(
            request.POST['name']))

    if request.method == 'POST' and 'next' in request.POST:
        return redirect(request.POST['next'])
    else:
        return redirect('cdmi:browse', site.id, path)


@user_passes_test(has_access_token)
def upload(request, site, path):
    site = Site.objects.get(id=site)
    path = re.sub('/+', '/', path)
    cdmi_path = true_path(path, site, request.user)

    if request.method == 'POST' and 'file' in request.FILES and site.can_browse:
        browser.handle_uploaded_file(
            site,
            request.FILES['file'],
            cdmi_path,
            request.session['access_token'])

        messages.success(request, '{} uploaded'.format(
            request.FILES['file'].name))

    if request.method == 'POST' and 'next' in request.POST:
        return redirect(request.POST['next'])
    else:
        return redirect('cdmi:browse', site.id, path)


@user_passes_test(has_access_token)
def mkdir(request, site, path):
    site = Site.objects.get(id=site)
    path = re.sub('/+', '/', path)
    cdmi_path = true_path(path, site, request.user)

    if request.method == 'POST' and 'name' in request.POST and site.can_browse:
        browser.handle_create_directory(
            site,
            request.POST['name'],
            cdmi_path,
            request.session['access_token'])

        messages.success(request, '{}/{} created'.format(
            path, request.POST['name']))

    if request.method == 'POST' and 'next' in request.POST:
        return redirect(request.POST['next'])
    else:
        return redirect('cdmi:browse', site.id, path)


class CdmiWebView(UserPassesTestMixin, generic.TemplateView):
    redirect_field_name = 'next'

    def test_func(self):
        return has_access_token(self.request.user)


class BrowserView(CdmiWebView):
    template_name = 'cdmi/browse.html'

    def dispatch(self, request, site, path):
        if site:
            self.site = Site.objects.get(id=site)
        else:
            self.site = Site.objects.get(default=True)

        # Remove leading '/', replace multiple slashes
        clean_path = re.sub('/+', '/', path).lstrip('/')
        clean_path = clean_path + '/' if clean_path and clean_path[-1] != '/' else clean_path
        if clean_path == path:
            self.path = path
            return super().dispatch(request, site, path)
        else:
            return redirect('cdmi:browse', site, clean_path)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        path = true_path(self.path, self.site, self.request.user)

        logger.debug("Browsing path '{}'".format(path))

        try:
            if self.site.can_browse:
                browser.handle_create_directory(
                    self.site, os.path.join(self.site.root_container, self.request.user.username), '',
                    self.request.session['access_token'])

            context['object_list'] = cdmi.list_objects(
                self.request,
                self.site, path, self.request.session['access_token'])
        except (ConnectionError, NotConnection, RemoteParentNotFound) as e:
            msg = '{}: {}'.format(self.site.site_uri, str(e))

            logger.warning(msg)
            messages.error(self.request, msg)

        except CdmiError as e:
            msg = '{}: {}'.format(e.dict.get('url', self.site.site_uri), e.dict['msg'])

            logger.warning(msg)
            messages.error(self.request, msg)

        return context


class IndexView(CdmiWebView):
    template_name = 'cdmi/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['sites'] = Site.objects.all()

        context['qualities_of_service'] = []
        for site in context['sites']:
            try:
                site.root_container = cdmi.get_status(
                    site, '/',
                    self.request.session['access_token'])
            except (ConnectionError, CdmiError) as e:
                msg = '{}: {}'.format(e.dict.get('url', site.site_uri), e.dict['msg'])

                logger.warning(msg)
                messages.warning(self.request, msg)

            try:
                qoses = cdmi.get_all_capabilities(
                    site.site_uri,
                    self.request.session['access_token'])
            except (ConnectionError, CdmiError) as e:
                msg = '{}: {}'.format(e.dict.get('url', site.site_uri), e.dict['msg'])

                logger.warning(msg)
                messages.error(self.request, msg)
            else:
                for qos in qoses:
                    qos['site'] = site

                context['qualities_of_service'] += qoses

        return context

cdmi/templates/cdmi/browse.html
{% extends "cdmi/root.html" %}
{% load static %}
{% load utils %}

{% block title %}{{ view.site.site_name }} - {% if view.site.root_container %}/{{ view.site.root_container }}{% endif %}/{{ view.path }}{% endblock %}

{% block head %}
<script>
  {% include 'cdmi/browse.js' %}
</script>
{% endblock %}

{% block body %}
<div class="container">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        {% if view.site.logo_uri %}
        <a class="navbar-brand" style="padding: 5px 15px"><img src="{{ view.site.logo_uri }}" height="40"></a>
        {% endif %}
        <a class="navbar-brand" href="#"><strong>{{ view.site.site_uri }}{% if view.site.root_container %}/{{ view.site.root_container }}{% endif %}</strong>/{{ view.path }}</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <button data-toggle="modal"
                    {% if not view.site.can_browse %}
                    title="Unavailable for this CDMI site"
                    {% else %}
                    title="Create Directory via {{ view.site.storage.access_type }}"
                    data-target="#mkdir"
                    {% endif %}
                    class="btn btn-primary
                           {% if not view.site.can_browse %}disabled{% endif %}">
              Create Directory
            </button>
          </li>
          <li>
            <button data-toggle="modal"
                    {% if not view.site.can_browse %}
                    title="Unavailable for this CDMI site"
                    {% else %}
                    title="Upload File via {{ view.site.storage.access_type }}"
                    data-target="#upload"
                    {% endif %}
                    class="btn btn-primary
                           {% if not view.site.can_browse %}disabled{% endif %}">
              Upload File
            </button>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>
</div>

<div class="container">
  {% if object_list or view.path %}
  <table class="table sortable" style="font-size:14px">
    <thead><tr>
        <th data-defaultsort="asc">Name</th>
        <th>Type</th>
        <th>Current QoS</th>
        <th data-defaultsort="disabled"></th>
        <th data-defaultsort="disabled">Target QoS</th>
        <th data-defaultsort="disabled"></th>
    </thead>
    <tbody>
      {% if view.path %}
      <tr>
        <td>
          <a href="{% url 'cdmi:browse' view.site.id view.path|dirname %}" method="get">
            ../
          </a>
        </td>
        <td>Directory</td>
        <td></td>
        <td></td>
        <td></td>
        <td>
            <div class="btn bare-btn btn-small" style="color: white">nil</div>
        </td>
      </tr>
      {% endif %}
      {% for o in object_list %}
      <tr>
        {% if o.type == "File" %}
        <td>
          {{ o.name }}
        </td>
        {% else %}
        <td>
          <a href="{% if view.path %}
                    {% url 'cdmi:browse' view.site.id view.path|pathjoin:o.name %}
                   {% else %}
                    {% url 'cdmi:browse' view.site.id o.name %}
                   {% endif %}">
            {{ o.name }}
          </a>
        </td>
        {% endif %}
        <td>
          {{ o.type }}
        </td>
        <td id="qos-{{ o.name|slugify }}">
          <script>
            $("#qos-{{ o.name|slugify }}").makeqosentry(
                "{{ o.capabilities_name }}",
                {
                  {% if capabilities_storage_lifetime %}
                  cdmi_data_storage_lifetime: "{{ o.capabilities_storage_lifetime }}",
                  {% endif %}
                  cdmi_capability_lifetime: "{{ o.capabilities_lifetime }}",
                  cdmi_capability_lifetime_action: "{{ o.capabilities_lifetime_action }}",
                  cdmi_latency: "{{ o.capabilities_latency }}",
                  cdmi_throughput: "{{ o.capabilities_throughput }}",
                  cdmi_data_redundancy: "{{ o.capabilities_redundancy }}",
                  cdmi_geographic_placement: {{ o.capabilities_geolocation|safe }},
                });
          </script>
        </td>
        <td style="width: 200px">
          <img id="progress-{{ o.name|slugify }}"
               src="{% static 'cdmi/img/progress.gif' %}"
               style="display: none"
               alt="loading" width="150">
        </td>
        <td id="entry-{{ o.name|slugify }}"
            data-name="{{ o.name }}"
            data-type="{{ o.type }}"
            data-id="{{ o.name|slugify }}">
          <div id="target-{{ o.name|slugify }}"
              style="display: none">
            {{ o.capabilities_target|basename }}
          </div>
          <div id="select-{{ o.name|slugify }}"
               class="dropdown">
            <!-- <li class="dropdown"> -->
            <a href="#" class="dropdown-toggle{% if not o.capabilities_allowed %} disabled{% endif %}"
               {% if not o.capabilities_allowed %}
               style="cursor: not-allowed; text-decoration: none"
               title="No transitions available for {{ o.capabilities_name }}"
               {% endif %}
               data-toggle="dropdown" role="button"
               aria-haspopup="true" aria-expanded="false">
              Select<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              {% for allowed in o.capabilities_allowed %}
              <li>
                <button class="btn btn-link"
                        onclick="$('#entry-{{ o.name|slugify }}').changeqos('{{ allowed }}')">
                  {{ allowed|basename }}
                </button>
              </li>
              {% endfor %}
            </ul>
            <!-- </li> -->
          </div>
        </td>
        <td>
          <form action="{% url 'cdmi:delete' view.site.id view.path %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="name" value="{{ o.name }}" />
            <button class="btn bare-btn btn-small
                           {% if not view.site.can_browse %}disabled{% endif %}"
                    {% if view.site.can_browse %}
                    title="Delete file via {{ view.site.storage.access_type }}"
                    {% else %
                    title="Unavailable for this CDMI site"
                    {% endif %}
                    type="submit" style="color: red">Delete</button>
          </form>
        </td>
      </tr>
      <script>
        $(document).ready(function() {
          {% if o.capabilities_target %}
          message('info', "Found {{ o.name }} in transition. Polling in {{ o.capabilities_polling }}ms");
          $("#entry-{{ o.name|slugify }}").poll({{ o.capabilities_polling }});
          $("#target-{{ o.name|slugify }}").makeqosentry(
              "{{ o.capabilities_target }}",
              {{ o.capabilities_target_metadata|safe }}
          );
          {% endif %}
        });
      </script>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}
</div>

<!-- Modal -->
<div class="modal fade" id="upload" tabindex="-1" role="dialog" aria-labelledby="uploadLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="uploadLabel">Upload file</h4>
      </div>
      <div class="modal-body">
        <form action="{% url 'cdmi:upload' view.site.id view.path %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <input type="file" id="file" name="file" required>
            <p class="help-block">Search for files to upload.</p>
            <input type="hidden" name="next" value="{{ request.get_full_path }}" />
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Upload</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="mkdir" tabindex="-1" role="dialog" aria-labelledby="mkdirLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="mkdirLabel">Create Directory</h4>
      </div>
      <div class="modal-body">
        <form action="{% url 'cdmi:mkdir' view.site.id view.path %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <input type="text" id="name" name="name" required>
            <p class="help-block">Name of directory</p>
            <input type="hidden" name="next" value="{{ request.get_full_path }}" />
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Create</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

cdmi/templates/cdmi/dict.html
{% load utils %}

{% if object %}
{% if object|is_list %}
<ul class="list">
  {% for element in object %}
  <li class="list-item" style="text-align: left">
    {% include 'cdmi/dict.html' with object=element %}
  </li>
  {% endfor %}
</ul>
{% elif object|is_dict %}
<table class="table">
  <tbody>
    {% for key, value in object.items %}
    <tr>
      <td>{{ key|cut:"cdmi_"|replace:"_, "|capfirst }}</td>
      <td>{% include 'cdmi/dict.html' with object=value %}</td>
    {% endfor %}
  </tbody>
</table>
{% elif object|is_string and object|is_url %}
<a href="{{ object }}">{{ object }}</a>
{% elif object|isoduration %}
{{ object|isoduration }}
{% else %}
{{ object }}
{% endif %}
{% endif %}

cdmi/templates/cdmi/index.html
{% extends "cdmi/root.html" %}
{% load static %}
{% load utils %}

{% block title %}QoS View{% endblock %}

{% block head %}
<script>
  {% include 'cdmi/index.js' %}
</script>
{% endblock %}

{% block body %}
<div class="container">
  <div class="container">
    <h1>Available Qualities of Storage</h1>
    <table class="table table-hover sortable"
           id="qos">
      <thead>
        <tr>
          <th data-defaultsort="disabled"></th>
          <th data-defaultsort="asc">Name</th>
          <th>Access Latency [ms]</th>
          <th>Number of Copies</th>
          <th>Storage Lifetime</th>
          <th>Location</th>
          <th>Storage type</th>
          <th>Available Transitions</th>
        </tr>
      </thead>
      <tbody>
        {% for qos in qualities_of_service %}
        <tr style="cursor: pointer;" data-toggle="collapse"
            data-target="#details-{{ qos.url|slugify }}">
          <td><img src="{{ qos.site.logo_uri }}" height="20"></td>
          <td>{{ qos.name }}</td>
          <td>{{ qos.latency }}</td>
          <td>{{ qos.copies }}</td>
          <td>
            {% if  qos.metadata.cdmi_data_storage_lifetime %}
            {{ qos.metadata.cdmi_data_storage_lifetime|isoduration }}
            {% endif %}
          </td>
          <td>{{ qos.location|join:", " }}</td>
          <td data-value="{{ qos.storage_types|slugify }}">
            {% for type in qos.storage_types %}
            <img title="{{ type|capfirst }}"
                 src="{% get_static_prefix %}cdmi/img/{{ type }}.png"
                 height="20">
            <small>{{ type|capfirst }}</small>{% if not forloop.last %}, {% endif %}
            {% empty %}
            <img title="Other"
                 src="{% static 'cdmi/img/other.png' %}"
                 height="20">
            {% endfor %}
          </td>
          <td>{{ qos.transitions|join:", " }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    
    <div id="details">
      {% for qos in qualities_of_service %}
      <div class="collapse"
           id="details-{{ qos.url|slugify }}">
        <h2 class="alignleft">{{ qos.name }}</h2>
        <h2 class="alignright">
          <a class="btn btn-primary" href="{% url 'cdmi:browse' qos.site.id '' %}">Browse</a>
        </h2>
        <table class="table">
          <tbody>
            <tr>
              <td>CDMI URL</td>
              <td><a style="text-decoration: none">{{ qos.url }}</a></td>
            </tr>
            <tr>
              <td>Exported via</td>
              <td>
                {% if qos.site.root_container.exports %}
                {% include 'cdmi/dict.html' with object=qos.site.root_container.exports %}
                {% else %}
                <em>Unavailable for this CDMI server</em>
                {% endif %}
              </td>
            </tr>
            <tr>
              <td>Metadata</td>
              <td>
                {% include 'cdmi/dict.html' with object=qos.metadata %}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

cdmi/templates/cdmi/root.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>CDMI Web - {% block title %}{% endblock %}</title>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'cdmi/js/jquery-3.1.1.min.js' %}"></script>

    <!-- Twitter Bootstrap -->
    <script src="{% static 'cdmi/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'cdmi/css/bootstrap.min.css' %}" />

    <!-- Sortable Bootstrap table: https://github.com/drvic10k/bootstrap-sortable -->
    <script src="{% static 'cdmi/js/moment.min.js' %}"></script>
    <script src="{% static 'cdmi/js/bootstrap-sortable.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'cdmi/css/bootstrap-sortable.css' %}" />

    <!-- Custom -->
    <link rel="stylesheet" type="text/css" href="{% static 'cdmi/css/custom.css' %}" />

    <script>
      {% include 'cdmi/root.js' %}
    </script>

    {% block head %}
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <div id="loadingDiv" class="navbar-brand">
            <img src="{% static 'cdmi/img/loader.gif' %}" alt="loading" height="25px">
          </div>
          <a class="navbar-brand" href="/">CDMI Web</a>
        </div>
        <p class="navbar-text">Logged in as: {{ request.user.username }}</p>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'openid:logout' %}">Logout</a></li>
        </ul>
      </div>
    </nav>
    {% block body %}
    {% endblock %}
    <div class="container">
      <table id="messages" class="table">
        <tbody>
          {% for message in messages %}
          <tr{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            <td>{{ message }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </body>
</html>